### ISSUE TITLE
failed to run custom build command for `dlib-face-recognition v0.3.0` on Fedora 38

### ISSUE THREAD

**Issue by albx79** [podo-os/dlib-face-recognition#21]
I'm getting the error above when trying to build using cargo on Fedora 38 with g++ 13.

The failure seems to be due to a number of `... function uses ‘auto’ type specifier without trailing return type` errors. (I'm attaching the output of `cargo build 2> error.log`).

According to StackOverflow (https://stackoverflow.com/questions/44798728/warning-function-uses-auto-type-specifier-without-trailing-return-type), that code can only be compiled with C++14. I've noticed that the latest release of gcc is version 13, so I wonder how can this code be compiled at all.

Any help is greatly appreciated. 

Thanks

[error.log](https://github.com/ulagbulag/dlib-face-recognition/files/11614408/error.log)

**Comment by JSanchesDovichi** [comment]
This seems to be a duplicate on #18 .
Dlib started using c++14 standard, and that has caused some breaks, but otherwise, a easy fix. (Fixed in #22.)
The GCC collection version 13 does not correlate to the c++ standard version. c++14 had initial support in GCC 4.9, so this shoudn`t be a problem.

**Comment by HoKim98** [comment]
Could you check the latest commit?

**Comment by albx79** [comment]
I can confirm that it works with the latest commit, thanks!
