### ISSUE TITLE
It works on Arch Linux

### ISSUE THREAD

**Issue by Madoshakalaka** [podo-os/dlib-face-recognition#29]
I tried to run the draw example with the `build-native` feature. It didn't work initially even when I had `blas`. I installed the `extra/openblas` package but it still didn't work. It worked perfectly after I installed `extra/blas-openblas`

**Comment by HoKim98** [comment]
Thanks! It allowed me to create a convenient document for using crate in Arch Linux. Could you mind to check the updated document when you have time?

**Comment by Madoshakalaka** [comment]
That looks good to me! Also, I also tried installing dlib with `pacman -S dlib` without using the `build-native` feature, it also worked for me.

**Comment by HoKim98** [comment]
You mean `yay -S dlib`? I tested on my Arch desktop and got an error that `dlib` is not an official package. Or do you have a custom repo?

**Comment by Madoshakalaka** [comment]
> You mean `yay -S dlib`? I tested on my Arch desktop and got an error that `dlib` is not an official package. Or do you have a custom repo?

you are right, sorry. ~And please use paru instread of yay cuz paru is written in Rust~

**Comment by HoKim98** [comment]
Really? I didn't know that `paru` is the more attractive one. Anyway, thanks for giving me a hint!

**Comment by HoKim98** [comment]
Updated! https://github.com/ulagbulag/dlib-face-recognition/commit/079158d821f0e85e4e0cc0c37a8f69b56f44db42

**Comment by HoKim98** [comment]
Closing by resolved.
