### ISSUE TITLE
[Possible bug] Error adding symbols: DSO missing from command line 

### ISSUE THREAD

**Issue by JSanchesDovichi** [podo-os/dlib-face-recognition#5]
Platform: Linux(x64) 

Behaviour: Running scripts fails at linking stage, specifically looking for libcblas (libcblas.so.3).

Unsure if Linux requires cblas instead of blas, but i tried it with blas, and still same error.

**Comment by HoKim98** [comment]
Thank you for issuing the problem.

Could you specify your environment?

* OS: Linux dist & version
* Packages Installed: especially related to blas
    * ex) Ubuntu: `sudo apt list --installed "*blas*"`

**Comment by JSanchesDovichi** [comment]
OS: Manjaro Linux x64 (based on Arch Linux) 21.2.2
Packages installed: blas and cblas.

I can confirm that with both installed, linking fails upon trying to link to blas, but properly works when linking with cblas.

**Comment by JSanchesDovichi** [comment]
Fixed he issue: i had a dependency link fail, now it's working fine.
Sorry for the unnecessary PR/Issue!

**Comment by HoKim98** [comment]
Glad to fix the problem!
