### ISSUE TITLE
CMAKE build for dlib-sys failing on cargo build

### ISSUE THREAD

**Issue by MoeAl-Ani** [podo-os/dlib-face-recognition#8]
Hi, can you give me access to the repo?  I would like to submit a pull request.

thank you.

**Comment by HoKim98** [comment]
Feel free to make a new PR, but I think that no touching about commits are not recommmended.

**Comment by MoeAl-Ani** [comment]
Hi, 

I have created a PR,

https://github.com/ulagbulag-village/dlib-face-recognition/pull/9

please review when you have time.
